### ISSUE TITLE
How to set custom annotation on validation route?

### ISSUE THREAD

**Issue by ThiefMaster** [tnozicka/openshift-acme#102]
In my organization's OpenShift cluster only routes with a special annotation `router.xxx.tld/network-visibility: Internet` are accessible from the public internet. Is there any way I can configure openshift-acme to add such an annotation to the route it creates?

**Environment**:
- OpenShift/Kubernetes version (use `oc/kubectl version`): v3.11.0+cbab8ee-94

@tnozicka

**Comment by ThiefMaster** [comment]
OK after looking at the code this doesn't seem to be possible, Forking it worked fine but it'd be nice if this could somehow be done using an environment variable or an annotation on the main route..

```diff
diff --git a/pkg/controllers/route/exposer.go b/pkg/controllers/route/exposer.go
index ee2dd24a068a917fa512c91bde0f8b5cf479c038..c996797f4c23f917c08e3811c860a6e54860f75f 100644
--- a/pkg/controllers/route/exposer.go
+++ b/pkg/controllers/route/exposer.go
@@ -165,6 +165,10 @@ func (e *Exposer) Expose(c *acme.Client, domain string, token string) error {
 		api.ExposerForLabelName: string(e.route.UID),
 	}
 
+	annotations := map[string]string{
+		"router.xxx.xxx/network-visibility": "Internet",
+	}
+
 	// Route can only point to a Service in the same namespace
 	// but we need to redirect ACME challenge to this controller
 	// usually deployed in a different namespace.
@@ -188,6 +192,7 @@ func (e *Exposer) Expose(c *acme.Client, domain string, token string) error {
 				},
 			},
 			Labels: labels,
+			Annotations: annotations,
 		},
 		Spec: routev1.RouteSpec{
 			Host: domain,
```

**Comment by rhmms** [comment]
Same issue here. We use shareded router (internal, external etc. etc. based on Annotations). So general annotation support would be great. We also use split DNS. Copying the labels from the route would be a simple approach, however it would not allow for internal routes using openshift-acme. Having another notation on the souce route that we could copy would make a rather generic solution.

**Comment by tnozicka** [comment]
with https://github.com/tnozicka/openshift-acme/pull/92 the exposer route now inherits all properties of the user route
