### ISSUE TITLE
Cert request coming back from Let's Encrypt as Invalid

### ISSUE THREAD

**Issue by pacepace** [tnozicka/openshift-acme#107]
**What happened**:
I installed a new route and instructed the acme service to request a certificate for it by adding the appropriate yaml.  The additional auth route was created, I can go to this route and see the auth code, but when Let's Encrypt goes to authenticate it, the request returns as invalid.  In looking at the error, Let's Encypt's sample HTML is from my site not from the auth route that was created and is working for me.

**What you expected to happen**:
Expected a cert to be installed.

**How to reproduce it (as minimally and precisely as possible)**:
Create route, add the yaml to make it request a certificate monitor the logs for the error.

**Anything else we need to know?**:
This was working for about a year, it stopped working a week or two ago.  I've got about 30 certs that this was managing, they are all going to expire in a couple months.  I upgraded from the previous release to 0.8.0 and that didn't change the behavior.

**Environment**:
- OpenShift/Kubernetes version (use `oc/kubectl version`):
OpenShift 3.9
openshift-acme 0.8.0

**Comment by tnozicka** [comment]
Would you mind sharing the controller logs and yaml for the affected objects?

**Comment by pacepace** [comment]
The issue stopped about a week I reported it and hasn't popped back up again.  I will get the logs if it does and re-open this ticket.
