### ISSUE TITLE
[DOC] Does openshift-acme can be used for replacing internal certificates

### ISSUE THREAD

**Issue by rmahroua** [tnozicka/openshift-acme#112]
**What would you like to be added**:
Documentation on whether openshift-acme can be used for updating the internal certificates that the API/Oauth server, routes, etc. present.

**Why is this needed**:
Get clarification on whether this project can be used for internal certificates or only routes for applications.
To clarify, what I mean by internal certificates are certs that "public" services use (Grafana, Prometheus, OAuth), and not the "internal" ones, such as the ones that the kubelets use to authenticate to the API or the ones that the Etcd cluster uses.

@tnozicka

**Comment by tnozicka** [comment]
I think everything except the apiserver is exposed via a Route so it shouldn't be hard. 
The apiserver cert impossible to get with http-01 validation as it's IP and traffic ar distinct from the router. You could wrap it in a Route and Service through and just redirect the traffic there.

I'll try to write an e2e with it and some docs when I get the time.
