### ISSUE TITLE
single namespace deployment does not work due to hard coded namespace acme-controller

### ISSUE THREAD

**Issue by DanielFroehlich** [tnozicka/openshift-acme#115]
Deployed to OCP V4.3.x today, using the single namespace approach, just copy pasted from the docs.
Did not work, in the openshift-acme controller pod, I saw tons of failure "not permitted to list Routes in namespace acme-controller".
Could work arround by editing the deployment and changeing
https://github.com/tnozicka/openshift-acme/blob/1e8bdea1527baee50f3866be458619f6a3251cb5/deploy/single-namespace/deployment.yaml#L27
to point to my namespace

@tnozicka - great work btw!

**Comment by tnozicka** [comment]
Thanks. 

Yeah, that was on my list as well. looks like @rbo already has a PR https://github.com/tnozicka/openshift-acme/pull/114

**Comment by rbo** [comment]
Solved since merged PR.
