### ISSUE TITLE
must delete image stream before upgrading from v1

### ISSUE THREAD

**Issue by djdevin** [tnozicka/openshift-acme#119]
Upgrading from v1, I ran the cluster wide steps in the deployment guide.

The new pods failed. I checked the image stream and it was still using the old v1 images. I didn't catch it but it was some error about Unknown parameter --expose...something (sorry), so I figured the image was still out of date.

I deleted the imagestream and re ran all the deployment commands and everything worked because it brought in the new v2 image.

(Also, thanks for this project!)

oc v3.11.0+8de5c34
kubernetes v1.10.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://xxx:443
openshift v3.11.0+bdd37ad-314
kubernetes v1.11.0+d4cacc0

@tnozicka

**Comment by tnozicka** [comment]
yeah, that's expected. until we have an operator to manage our objects the deploy steps assume clean namespace - might worth to mention it explicitly there though
