### ISSUE TITLE
Annotate route with error

### ISSUE THREAD

**Issue by andrewklau** [tnozicka/openshift-acme#12]
It'll be helpful to have the annotations added on the error status. 

eg when a cert is added we get.

```
    kubernetes.io/tls-acme.last-update-time: '2017-06-16T05:51:36Z'
```
If a renew fails or we can't authorise the domain, it would be nice to have a log of the error in the annotation so a user who doesn't have access to openshift-acme logs can at least see what could be wrong.

**Comment by tnozicka** [comment]
+1; e.g. https://github.com/tnozicka/openshift-acme/blob/1895421df94c968cef99bf409030b62d701a1187/pkg/openshift/controllers/acme/dbcertentry.go#L81

**Comment by tnozicka** [comment]
fixed in https://github.com/tnozicka/openshift-acme/pull/48
the controller emits events now
