### ISSUE TITLE
Openshift-ACME stopped working

### ISSUE THREAD

**Issue by pret691** [tnozicka/openshift-acme#126]
**What happened**:
I used the openshift-acme (v2) successfully a month ago. Today I added the annotation to a new route, but nothing happened. 

**What you expected to happen**:
a certificate should be assigned or some kind of error/status message in the logs regarding this

**How to reproduce it (as minimally and precisely as possible)**:
1. Add new Route
2. Add to route's yaml:
`  annotations:
    kubernetes.io/tls-acme: 'true'`

**Anything else we need to know?**:
Since I made no changes, I checked the openshift-acme installation. 
2 pods running:

the logs of the first one shows:

> I0512 16:00:28.678950       1 reflector.go:188] Listing and watching *v1.LimitRange from k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108
I0512 16:00:28.680075       1 reflector.go:188] Listing and watching *v1.LimitRange from k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108
E0512 16:00:28.681679       1 reflector.go:156] k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108: Failed to list *v1.LimitRange: limitranges is forbidden: User "system:serviceaccount:acme:openshift-acme" cannot list limitranges in the namespace "acme": no RBAC policy matched
E0512 16:00:28.681918       1 reflector.go:156] k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108: Failed to list *v1.LimitRange: limitranges is forbidden: User "system:serviceaccount:acme:openshift-acme" cannot list limitranges at the cluster scope: no RBAC policy matched
I0512 16:00:29.115803       1 reflector.go:432] k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108: Watch close - *v1.Secret total 0 items received
I0512 16:00:29.166473       1 reflector.go:338] k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108: watch of *v1.Secret ended with: The resourceVersion for the provided watch is too old.

Second pod

> I0512 05:19:18.406025       1 leaderelection.go:352] lock is held by openshift-acme-68f96bc4cf-9shhs_a11c13be-72c7-4201-a241-f38728d5371e and has not yet expired
I0512 05:19:18.406072       1 leaderelection.go:247] failed to acquire lease acme/acme-controller-locks
I0512 05:19:30.366674       1 leaderelection.go:352] lock is held by openshift-acme-68f96bc4cf-9shhs_a11c13be-72c7-4201-a241-f38728d5371e and has not yet expired
I0512 05:19:30.366778       1 leaderelection.go:247] failed to acquire lease acme/acme-controller-locks

**Environment**:
- OpenShift/Kubernetes version (use `oc/kubectl version`):#
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0

@tnozicka

**Comment by tnozicka** [comment]
> or some kind of error/status message in the logs regarding this

E0512 16:00:28.681679 1 reflector.go:156] k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108: Failed to list *v1.LimitRange: limitranges is forbidden: User "system:serviceaccount:acme:openshift-acme" cannot list limitranges in the namespace "acme": no RBAC policy matched
E0512 16:00:28.681918 1 reflector.go:156] k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108: Failed to list *v1.LimitRange: limitranges is forbidden: User "system:serviceaccount:acme:openshift-acme" cannot list limitranges at the cluster scope: no RBAC policy matched

I assume this was redeployed with newer version of openshift-acme and not updating RBAC role https://github.com/tnozicka/openshift-acme/blob/master/deploy/cluster-wide/clusterrole.yaml

**Comment by pret691** [comment]
Great, it works! Thank you very much for this fast reply!
