### ISSUE TITLE
Allow configure requests/limits for exposer pods

### ISSUE THREAD

**Issue by nevidanniu** [tnozicka/openshift-acme#127]
**What would you like to be added**:
Allow to configure limits and requests for exposer pod
**Why is this needed**:
Often openshift projects have configured quotas for resource usage, one of them is request/limit ratio. Currently you have to adjust this ratio to what is hardcoded in exposer config or you will not be allowed to create a pod and get following error:
` Warning  FailedCreate  1m (x7 over 3m)  replicaset-controller  (combined from similar events): Error creating: pods "exposer-d51keecnpkmle6n94kvq4cbt0ceqtmp7ogbdtuiu3ldspjhpmokdsmv" is forbidden: cpu max limit to request ratio per Container is 12, but provided ratio is 12.500000.`

@tnozicka

**Comment by tnozicka** [comment]
what version are you on? does it have https://github.com/tnozicka/openshift-acme/pull/116 ?
