### ISSUE TITLE
v1 to v2 migration path

### ISSUE THREAD

**Issue by rporres** [tnozicka/openshift-acme#129]
We have a few deployments of openshift-acme still running with v1. Is there a migration path to run v2 there or will it just work with the existing routes and secrets removing the v1 deployments, services, etc and installing the v2 ones?

Related to #119

Thx for all the work here, @tnozicka. Great stuff!

**Comment by tnozicka** [comment]
The migration from v1 to v2 doesn't require any action except replacing the deployment resources.

Always apply the deployment together with other resources (like serviceaccount, roles, ..) from the same version and delete resources that are no longer there like the imagestream.

**Comment by rporres** [comment]
Thx, @tnozicka
