### ISSUE TITLE
Introduce our public helm chart

### ISSUE THREAD

**Issue by ThoTischner** [tnozicka/openshift-acme#130]
**What would you like to be added**:
We have a public helm chart repo: https://bitsbeats.github.io/helm-charts/
There is an openshift-acme chart, that can be used to install the openshift-acme controller.

**Why is this needed**:
Easy installation via ci/cd

@tnozicka

**Comment by tnozicka** [comment]
Sorry, we are not going to support helm as deployment method.
/close

(There is going to be an operator for openshift-acme though.)

**Comment by ThoTischner** [comment]
Okay thanks for your efforts
