### ISSUE TITLE
[Information Request] docker image update policy

### ISSUE THREAD

**Issue by maorfr** [tnozicka/openshift-acme#137]
Hello and thank you for all the amazing work!

We would like to understand the policy behind updating images in quay.io/tnozicka/openshift-acme.

When are images pushed and updated?

Thank you very much again!

**Comment by tnozicka** [comment]
Hi @maorfr,

thanks and sorry this slipped out of my radar. I've updated the issue template a while back to automatically cc me.

The images are built from master and pushed to `registry.svc.ci.openshift.org/openshift-acme/0.9` (tags `controller`, `exposer`) right after a merge to master happens.
https://github.com/openshift/release/blob/02ba446/ci-operator/config/tnozicka/openshift-acme/tnozicka-openshift-acme-master.yaml
It is being mirrored to quay.io in about an hour it think by this spec
https://github.com/openshift/release/blob/02ba446e097581806a3ec25345ede712486afc8a/core-services/image-mirroring/tnozicka/mapping_tnozicka_openshift-acme

**Comment by maorfr** [comment]
thanks a lot @tnozicka.

cc @rporres

**Comment by rporres** [comment]
Hi @tnozicka. Could you explain the reason behind not having versioned tags? You're only keeping a sort of `latest` and `0.9` tags for `exposer` and `controller` components...

**Comment by Alveel** [comment]
Gentle poke @tnozicka, also interested.
