### ISSUE TITLE
Route not creating from ingress after applying cluster-wide openshift-acme

### ISSUE THREAD

**Issue by rainbowjose** [tnozicka/openshift-acme#138]
**What happened**: Route not creating from ingress after applying cluster-wide openshift-acme.

**What you expected to happen**: route creating must work

**How to reproduce it (as minimally and precisely as possible)**:  
```
oc new-project acme
oc apply -fhttps://raw.githubusercontent.com/tnozicka/openshift-acme/master/deploy/cluster-wide/{clusterrole,serviceaccount,issuer-letsencrypt-live,deployment}.yaml
oc create clusterrolebinding openshift-acme --clusterrole=openshift-acme --serviceaccount="$( oc project -q ):openshift-acme" --dry-run -o yaml | oc apply -f -
oc project default
```

**Anything else we need to know?**:

**Environment**:
- OpenShift/Kubernetes version (use `oc/kubectl version`): OKD 4.5
- Others:

@tnozicka

**Comment by rainbowjose** [comment]
Not realated to acme, sorry.

**Comment by tux-o-matic** [comment]
@rainbowjose , did you actually managed to use the controller on a 4.x cluster?
Based on #140 we seem to be several facing issues on 4.x clusters.
