### ISSUE TITLE
Temporary exposer route got stuck

### ISSUE THREAD

**Issue by alex-sentsiurou** [tnozicka/openshift-acme#140]
**What happened:**
Certificate fails to get provisioned because controller creates and delete new exposer pods after a new route is added with kubernetes.io/tls-acme=true annotation.

**What you expected to happen:**
A valid ACME certificate should be assigned to the route (live environment is deployed).
Also, the exposer pod should be deleted after serving http challenge.

**How to reproduce it (as minimally and precisely as possible):**
Install cluster-wide live controller. Deploying a Sample Application (I tried with other routes and apps as well):
oc new-project example-project
oc create -fhttps://raw.githubusercontent.com/tnozicka/gohellouniverse/master/deploy/{deployment,service}.yaml
oc create route edge gohellouniverse --service=gohellouniverse
oc patch route gohellouniverse -p '{"metadata":{"annotations":{"kubernetes.io/tls-acme":"true"}}}'

**Anything else we need to know?:**
here's a part of controller logs (endless repeat):
```bash
I0715 12:23:50.814190       1 route.go:496] Started syncing Route "example-project/gohellouniverse"
I0715 12:23:50.815605       1 route.go:563] Route "example-project/gohellouniverse" needs new certificate: Route is missing CertKey
I0715 12:23:50.817162       1 route.go:607] Using ACME client with DirectoryURL "https://acme-v02.api.letsencrypt.org/directory"
I0715 12:23:51.632110       1 route.go:650] Route "example-project/gohellouniverse": Order "https://acme-v02.api.letsencrypt.org/acme/order/91391673/4216781579" is in "pending" state
I0715 12:23:51.632183       1 route.go:655] Route "example-project/gohellouniverse": Order "https://acme-v02.api.letsencrypt.org/acme/order/91391673/4216781579" contains 1 authorization(s)
I0715 12:23:51.930592       1 route.go:663] Route "example-project/gohellouniverse": order "https://acme-v02.api.letsencrypt.org/acme/order/91391673/4216781579": authz "https://acme-v02.api.letsencrypt.org/acme/authz-v3/5895984458": is in "pending" state
I0715 12:23:51.930725       1 route.go:690] route "example-project/gohellouniverse": order "https://acme-v02.api.letsencrypt.org/acme/order/91391673/4216781579": authz "https://acme-v02.api.letsencrypt.org/acme/authz-v3/5895984458": challenge "pending" is in "pending" state
I0715 12:23:51.931290       1 route.go:1001] exposer Route example-project/exposer-a22m8b0algd0o7t8h3b7fct2mfkhro3ehmjaq5tn54e03rj9tcbg isn't admitted yet
I0715 12:23:51.932334       1 route.go:498] Finished syncing Route "example-project/gohellouniverse"
```
```bash
$ oc get routes -w
NAME                                                           HOST/PORT                                                    PATH
                                          SERVICES                                                       PORT    TERMINATION   WILDCARD
exposer-a22m8b0algd0o7t8h3b7fct2mfkhro3ehmjaq5tn54e03rj9tcbg   HostAlreadyClaimed                                           /.well-known/acme-challenge/FrvghT_GdpJWJ0c0lDvh06LHO2iYc5yfsTV74E8_T0g   exposer-a22m8b0algd0o7t8h3b7fct2mfkhro3ehmjaq5tn54e03rj9tcbg   <all>   edge/Allow    None
exposer-gds3hchr7id62tm6vabsajrakkuq3prb5maj9uu06q2jgbmvcp6g   gohellouniverse-example-project.apps.okd4.okd.gomel.iba.by   /.well-known/acme-challenge/FrvghT_GdpJWJ0c0lDvh06LHO2iYc5yfsTV74E8_T0g   exposer-gds3hchr7id62tm6vabsajrakkuq3prb5maj9uu06q2jgbmvcp6g   <all>   edge/Allow    None
gohellouniverse                                                gohellouniverse-example-project.apps.okd4.okd.gomel.iba.by
                                          gohellouniverse                                                <all>   edge          None
```

The temporary route created for http challenge is responsive and returns the secret:
```bash
curl -X GET gohellouniverse-example-project.apps.okd4.okd.gomel.iba.by/.well-known/acme-challenge/FrvghT_GdpJWJ0c0lDvh06LHO2iYc5yfsTV74E8_T0g
FrvghT_GdpJWJ0c0lDvh06LHO2iYc5yfsTV74E8_T0g.N-dKBfHTEleCbUiR3NqK18i8l92p44zfceKQO2ZUxL8
```

**Environment (OKD 4.4 on bare metal):**
Client Version: 4.4.0-0.okd-2020-05-23-055148-beta5
Server Version: 4.4.0-0.okd-2020-05-23-055148-beta5
Kubernetes Version: v1.17.1

**Comment by tux-o-matic** [comment]
Same experience on OCP 4.3

**Comment by tux-o-matic** [comment]
@tnozicka, this is a blocker. If you don' have time on your hands to fix it, could you maybe point us in the area of the code that needs attention for a solution?

**Comment by JavierLeonPeris** [comment]
Same experience on OCP 4.5

**Comment by ggrames** [comment]
Same experience on OCP 4.5
is there already a workaround?

**Comment by JavierLeonPeris** [comment]
we couldn't solve it, we've also tried cert-manager but didn't work either.

**Comment by tnozicka** [comment]
Can you attach the full (redacted) yaml for those routes? I have tried with a few days old OCP 4.7-ci in AWS and the cert was provisioned and the temporary route was deleted.

It this happening consistently for you?
Does it recover when you delete the temporary routes?
What is the version of openshift-acme you are using?

**Comment by tux-o-matic** [comment]
Hey @tnozicka. There is a race condition and the acme controller creates the same route again which gets rejected by OCP since an older one declared the same Route.
It's nice to see you test this but don't you have an OCP release that is GA to compare with what we've been experiencing?
I'll let somebody else give an example.

**Comment by ggrames** [comment]
Hi,
these are the 2 exposer routes and the external which should get the cert
`apiVersion: v1
items:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      acme.openshift.io/status: |
        provisioningStatus:
          earliestAttemptAt: "2020-12-04T10:06:22.997585095Z"
          failures: 4
          orderStatus: pending
          orderURI: https://acme-v02.api.letsencrypt.org/acme/order/104951052/6558635295
          startedAt: "2020-12-04T10:06:22.997585095Z"
      kubernetes.io/tls-acme: "true"
    creationTimestamp: "2020-12-04T07:03:43Z"
    labels:
      app: docpipe5
    managedFields:
    - apiVersion: route.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:ingress: {}
      manager: openshift-router
      operation: Update
      time: "2020-12-04T07:03:43Z"
    - apiVersion: route.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubernetes.io/tls-acme: {}
          f:labels:
            .: {}
            f:app: {}
        f:spec:
          f:host: {}
          f:port:
            .: {}
            f:targetPort: {}
          f:tls:
            .: {}
            f:termination: {}
          f:to:
            f:kind: {}
            f:name: {}
            f:weight: {}
          f:wildcardPolicy: {}
      manager: Mozilla
      operation: Update
      time: "2020-12-04T09:17:14Z"
    - apiVersion: route.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:acme.openshift.io/status: {}
      manager: openshift-acme-controller
      operation: Update
      time: "2020-12-04T10:06:25Z"
    name: docpipe5-external
    namespace: documatrix-development
    resourceVersion: "206207691"
    selfLink: /apis/route.openshift.io/v1/namespaces/documatrix-development/routes/docpipe5-external
    uid: a824b36d-c039-483b-8725-35f86a320d93
  spec:
    host: docpipe5-external-documatrix-development.apps.ocp.3sit.at
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: docpipe5-8080
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: "2020-12-04T07:03:43Z"
        status: "True"
        type: Admitted
      host: docpipe5-external-documatrix-development.apps.ocp.3sit.at
      routerCanonicalHostname: apps.ocp.intern.3sit.at
      routerName: default
      wildcardPolicy: None
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      acme.openshift.io/exposer-id: docpipe5-external:https://acme-v02.api.letsencrypt.org/acme/order/104951052/6558635109:https://acme-v02.api.letsencrypt.org/acme/authz-v3/9064887962:https://acme-v02.api.letsencrypt.org/acme/chall-v3/9064887962/91z2Jw
      acme.openshift.io/exposer-key: documatrix-development/docpipe5-external
      acme.openshift.io/status: |
        provisioningStatus:
          earliestAttemptAt: "2020-12-04T10:05:46.490819596Z"
          failures: 4
          orderStatus: pending
          orderURI: https://acme-v02.api.letsencrypt.org/acme/order/104951052/6558635109
          startedAt: "2020-12-04T10:06:22.124060295Z"
      kubernetes.io/tls-acme: "true"
    creationTimestamp: "2020-12-04T10:06:24Z"
    labels:
      acme.openshift.io/exposer-uid: a824b36d-c039-483b-8725-35f86a320d93
      acme.openshift.io/temporary: "true"
      app: docpipe5
    managedFields:
    - apiVersion: route.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:port:
            .: {}
            f:targetPort: {}
      manager: Mozilla
      operation: Update
      time: "2020-12-04T09:17:14Z"
    - apiVersion: route.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:acme.openshift.io/exposer-id: {}
            f:acme.openshift.io/exposer-key: {}
            f:acme.openshift.io/status: {}
            f:kubernetes.io/tls-acme: {}
          f:labels:
            .: {}
            f:acme.openshift.io/exposer-uid: {}
            f:acme.openshift.io/temporary: {}
            f:app: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"a824b36d-c039-483b-8725-35f86a320d93"}:
              .: {}
              f:apiVersion: {}
              f:controller: {}
              f:kind: {}
              f:name: {}
              f:uid: {}
        f:spec:
          f:host: {}
          f:path: {}
          f:tls:
            .: {}
            f:insecureEdgeTerminationPolicy: {}
            f:termination: {}
          f:to:
            f:kind: {}
            f:name: {}
            f:weight: {}
          f:wildcardPolicy: {}
      manager: openshift-acme-controller
      operation: Update
      time: "2020-12-04T10:06:24Z"
    - apiVersion: route.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:ingress: {}
      manager: openshift-router
      operation: Update
      time: "2020-12-04T10:06:24Z"
    name: exposer-1fv03q7jublbj4a1i50q53aub2g21brui5hbegkfofsphn7pp7h0
    namespace: documatrix-development
    ownerReferences:
    - apiVersion: route.openshift.io/v1
      controller: true
      kind: Route
      name: docpipe5-external
      uid: a824b36d-c039-483b-8725-35f86a320d93
    resourceVersion: "206207653"
    selfLink: /apis/route.openshift.io/v1/namespaces/documatrix-development/routes/exposer-1fv03q7jublbj4a1i50q53aub2g21brui5hbegkfofsphn7pp7h0
    uid: 12e1fbfb-e4b7-4098-80c0-356cee764f44
  spec:
    host: docpipe5-external-documatrix-development.apps.ocp.3sit.at
    path: /.well-known/acme-challenge/o6IT_Jq0C3TTaCdtpbyVU_ce1dhDQgZrai7_uCGyVa0
    tls:
      insecureEdgeTerminationPolicy: Allow
      termination: edge
    to:
      kind: Service
      name: exposer-1fv03q7jublbj4a1i50q53aub2g21brui5hbegkfofsphn7pp7h0
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: "2020-12-04T10:06:24Z"
        status: "True"
        type: Admitted
      host: docpipe5-external-documatrix-development.apps.ocp.3sit.at
      routerCanonicalHostname: apps.ocp.intern.3sit.at
      routerName: default
      wildcardPolicy: None
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      acme.openshift.io/exposer-id: docpipe5-external:https://acme-v02.api.letsencrypt.org/acme/order/104951052/6558635295:https://acme-v02.api.letsencrypt.org/acme/authz-v3/9064887962:https://acme-v02.api.letsencrypt.org/acme/chall-v3/9064887962/91z2Jw
      acme.openshift.io/exposer-key: documatrix-development/docpipe5-external
      acme.openshift.io/status: |
        provisioningStatus:
          earliestAttemptAt: "2020-12-04T10:05:46.490819596Z"
          failures: 4
          orderStatus: pending
          orderURI: https://acme-v02.api.letsencrypt.org/acme/order/104951052/6558635295
          startedAt: "2020-12-04T10:06:22.997585095Z"
      kubernetes.io/tls-acme: "true"
    creationTimestamp: "2020-12-04T10:06:25Z"
    labels:
      acme.openshift.io/exposer-uid: a824b36d-c039-483b-8725-35f86a320d93
      acme.openshift.io/temporary: "true"
      app: docpipe5
    managedFields:
    - apiVersion: route.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:port:
            .: {}
            f:targetPort: {}
      manager: Mozilla
      operation: Update
      time: "2020-12-04T09:17:14Z"
    - apiVersion: route.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:acme.openshift.io/exposer-id: {}
            f:acme.openshift.io/exposer-key: {}
            f:acme.openshift.io/status: {}
            f:kubernetes.io/tls-acme: {}
          f:labels:
            .: {}
            f:acme.openshift.io/exposer-uid: {}
            f:acme.openshift.io/temporary: {}
            f:app: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"a824b36d-c039-483b-8725-35f86a320d93"}:
              .: {}
              f:apiVersion: {}
              f:controller: {}
              f:kind: {}
              f:name: {}
              f:uid: {}
        f:spec:
          f:host: {}
          f:path: {}
          f:tls:
            .: {}
            f:insecureEdgeTerminationPolicy: {}
            f:termination: {}
          f:to:
            f:kind: {}
            f:name: {}
            f:weight: {}
          f:wildcardPolicy: {}
      manager: openshift-acme-controller
      operation: Update
      time: "2020-12-04T10:06:25Z"
    - apiVersion: route.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:ingress: {}
      manager: openshift-router
      operation: Update
      time: "2020-12-04T10:06:25Z"
    name: exposer-gcl2qecrlhckaicnst3fn1e4cne88op30m2fvtpjoc74ve60jlqg
    namespace: documatrix-development
    ownerReferences:
    - apiVersion: route.openshift.io/v1
      controller: true
      kind: Route
      name: docpipe5-external
      uid: a824b36d-c039-483b-8725-35f86a320d93
    resourceVersion: "206207698"
    selfLink: /apis/route.openshift.io/v1/namespaces/documatrix-development/routes/exposer-gcl2qecrlhckaicnst3fn1e4cne88op30m2fvtpjoc74ve60jlqg
    uid: c871dcdb-73bd-4df1-815f-2b5bc6cfce98
  spec:
    host: docpipe5-external-documatrix-development.apps.ocp.3sit.at
    path: /.well-known/acme-challenge/o6IT_Jq0C3TTaCdtpbyVU_ce1dhDQgZrai7_uCGyVa0
    tls:
      insecureEdgeTerminationPolicy: Allow
      termination: edge
    to:
      kind: Service
      name: exposer-gcl2qecrlhckaicnst3fn1e4cne88op30m2fvtpjoc74ve60jlqg
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: "2020-12-04T10:06:25Z"
        message: route docpipe5-external already exposes docpipe5-external-documatrix-development.apps.ocp.3sit.at and is older
        reason: HostAlreadyClaimed
        status: "False"
        type: Admitted
      host: docpipe5-external-documatrix-development.apps.ocp.3sit.at
      routerCanonicalHostname: apps.ocp.intern.3sit.at
      routerName: default
      wildcardPolicy: None
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
`

**Comment by tnozicka** [comment]
Hi, 

I don't think this depends on OCP version used but more on how slow your infra/informers are and if the informers see the update before next sync loop on the same item. It should generate the same name for the same challenge and not to create a new one which is how it avoids the race. 
https://github.com/tnozicka/openshift-acme/blob/6955c94/pkg/controller/route/route.go#L694-L694 
Although the dump suggests otherwise:
```
creationTimestamp: "2020-12-04T10:06:24Z"
name: exposer-1fv03q7jublbj4a1i50q53aub2g21brui5hbegkfofsphn7pp7h0
path: /.well-known/acme-challenge/o6IT_Jq0C3TTaCdtpbyVU_ce1dhDQgZrai7_uCGyVa0
---
creationTimestamp: "2020-12-04T10:06:25Z"
name: exposer-gcl2qecrlhckaicnst3fn1e4cne88op30m2fvtpjoc74ve60jlqg
path: /.well-known/acme-challenge/o6IT_Jq0C3TTaCdtpbyVU_ce1dhDQgZrai7_uCGyVa0
```

Including `challengePath` would seem like an easy way to avoid it but I'd like to see the controller logs from around the time these 2 exposer routes were created to see `order.URI`, `authzURL` and `challenge.URI` values if possible.

**Comment by ggrames** [comment]
> 
> 
> Hi,
> 
> I don't think this depends on OCP version used but more on how slow your infra/informers are and if the informers see the update before next sync loop on the same item. It should generate the same name for the same challenge and not to create a new one which is how it avoids the race.
> https://github.com/tnozicka/openshift-acme/blob/6955c94/pkg/controller/route/route.go#L694-L695
> Although the dump suggests otherwise:
> 
> ```
> creationTimestamp: "2020-12-04T10:06:24Z"
> name: exposer-1fv03q7jublbj4a1i50q53aub2g21brui5hbegkfofsphn7pp7h0
> path: /.well-known/acme-challenge/o6IT_Jq0C3TTaCdtpbyVU_ce1dhDQgZrai7_uCGyVa0
> ---
> creationTimestamp: "2020-12-04T10:06:25Z"
> name: exposer-gcl2qecrlhckaicnst3fn1e4cne88op30m2fvtpjoc74ve60jlqg
> path: /.well-known/acme-challenge/o6IT_Jq0C3TTaCdtpbyVU_ce1dhDQgZrai7_uCGyVa0
> ```
> 
> Including `challengePath` would seem like an easy way to avoid it but I'd like to see the controller logs from around the time these 2 exposer routes were created to see `order.URI`, `authzURL` and `challenge.URI` values if possible.

Hi,
Today i have seen you have pushed today ad 13.00 middle european Time a new image to quay
I tried it again and i have seen, that the challenge route is now correct created.
No success at the moment with it

Here is the output of an openshift-acme pod:

[openshift-acme-pod-output.txt](https://github.com/tnozicka/openshift-acme/files/5652785/openshift-acme-pod-output.txt)

**Comment by tux-o-matic** [comment]
Can confirm success on OCP 4.6.

**Comment by ggrames** [comment]
have reinstalled the whole openshift acme app, with service account, roles, ...
Is the route for the renew in the same namespace in your setup?
Thx

**Comment by tux-o-matic** [comment]
@ggrames. The PR only touches the Controller code, not exposer. So if you used the example ```Deployment``` with *pull: Always* then force a redeploy of the controller, that should be enough.
If you had validation code pending, not sure if the new Controller will pick that up or if you should recreate the Route.
I tested cluster-wide setup, where the acme controller is in its own namespace.

**Comment by ggrames** [comment]
@tux-o-matic 
i have already recreated the route and yes i use pull always.
Also i have already scaled the openshift-acme pods to 0 und up to 2 again.
So it should be up2date
There have to be another problem.
