### ISSUE TITLE
Routes being deleted by openshift-acme

### ISSUE THREAD

**Issue by ykoyfman** [tnozicka/openshift-acme#144]
**What happened**:

Our public route that's set up for cert renewal by openshift-acme has been deleted a few times in the past few days by the openshift-acme pod:

```
#  oc logs openshift-acme-59bf8765dd-lqxvb | grep -i deleting
I1109 05:53:14.651548       1 route.go:252] Deleting Route istio-system/credit-card RV=94440977 UID=eed63fc9-e1c8-4e7b-aa99-c4d5e8b1e79a
I1111 18:53:16.111893       1 route.go:252] Deleting Route istio-system/credit-card RV=96404485 UID=7ac6f5a5-4cde-4c37-9d7d-3ca1c805dd42
I1112 14:21:57.570969       1 route.go:252] Deleting Route istio-system/credit-card RV=97032893 UID=a7ffece8-09ee-444a-9602-e37a11c557a9
```

Annotation is:

```
kubernetes.io/tls-acme: "true"
```

**What you expected to happen**:

That openshift-acme would not delete routes.

**How to reproduce it (as minimally and precisely as possible)**:

This started happening about 2 weeks after setting up openshift-acme, and it's not clear what is triggering the deletions.

**Environment**:
- OpenShift/Kubernetes version (use `oc/kubectl version`):

```
#  oc version
Client Version: 4.5.0-202004300829-5079abc
Server Version: 4.3.38
Kubernetes Version: v1.16.2+417b9fd
```

- Others:

@tnozicka

**Comment by tnozicka** [comment]
What leads you to think openshift-acme is deleting the Route? The log message is not saying that, although the phrasing there might be better. It just means it has observed the deletion through shared informers.
https://github.com/tnozicka/openshift-acme/blob/6955c949a5a55b75381f2698b274373f540a0acb/pkg/controller/route/route.go#L252

Have you check audit logs for kube-apiserver?

**Comment by ykoyfman** [comment]
Thanks, yeah, the way it's worded did make me think it was openshift-acme. I'll investigate some more and see if I can figure out what happened.

**Comment by ykoyfman** [comment]
Going to close this out - investigating whether another operator in my cluster was deleting this route during a reconciliation loop. Thanks for looking at it.
