### ISSUE TITLE
Exposer pods continue to run after cert is issued

### ISSUE THREAD

**Issue by lukastheblack** [tnozicka/openshift-acme#149]
I had to create a large amount of routes recently for work, and this deployment successfully issued lets encrypt certs for them. The problem is that I have 60+ exposer pods still running in the namespace, no errors in the openshift-acme logs, no errors on the pods themselves, and I'm confused as to how to remove them correctly. Please advise, and let me know what other information I can provide.

**Comment by lukeelten** [comment]
I have the same issue and found the problem.
The controller does not set the correct API Version in the owner reference of the dependent resources.
It sets the API Version to `v1` while `route.openshift.io/v1` would be the proper version for kubernetes to actually run garbage collection on those resources.
