### ISSUE TITLE
Failure to apply certificate on web console

### ISSUE THREAD

**Issue by darren-oxford** [tnozicka/openshift-acme#154]
**What happened**: Constant re-issue of certificates until rate limit exceeded for console route. Something seems to cause the CertKey to appear to be missing causing a new certificate order to be attempted.

**What you expected to happen**: Certificate to be issued once and applied to route.

**Environment**:
- OpenShift OKD bare metal install
- Server Version: 4.7.0-0.okd-2021-03-07-090821
- Kubernetes Version: v1.20.0-1046+5fbfd197c16d3c

**Example Log**
I0317 22:15:08.917432       1 route.go:496] Started syncing Route "openshift-console/console"
I0317 22:15:08.917633       1 route.go:563] Route "openshift-console/console" needs new certificate: Route is missing CertKey
I0317 22:15:08.917947       1 route.go:607] Using ACME client with DirectoryURL "https://acme-v02.api.letsencrypt.org/directory"
I0317 22:15:10.723922       1 route.go:650] Route "openshift-console/console": Order "https://acme-v02.api.letsencrypt.org/acme/order/115489376/8510418XXX" is in "ready" state
I0317 22:15:10.723955       1 route.go:1070] Route "openshift-console/console": Order "https://acme-v02.api.letsencrypt.org/acme/order/115489376/8510418XXX" successfully validated
I0317 22:15:16.007692       1 route.go:1092] Route "openshift-console/console": Order "https://acme-v02.api.letsencrypt.org/acme/order/115489376/8510418XXX": Certificate available at "https://acme-v02.api.letsencrypt.org/acme/cert/04bde7a3b76bf1cfecbc9ff87c627bfdd176"
I0317 22:15:16.029427       1 route.go:1276] Cleaning up temporary exposer for Route openshift-console/console (UID=71e8f2da-aaa0-4773-9a6c-dc3bc5ca90c4)
I0317 22:15:16.029837       1 route.go:226] Updating Route openshift-console/console RV=2585441->2585490 UID=71e8f2da-aaa0-4773-9a6c-dc3bc5ca90c4->71e8f2da-aaa0-4773-9a6c-dc3bc5ca90c4
I0317 22:15:16.039382       1 route.go:498] Finished syncing Route "openshift-console/console"
I0317 22:15:16.039431       1 route.go:496] Started syncing Route "openshift-console/console"
I0317 22:15:16.039801       1 route.go:559] Route "openshift-console/console" doesn't need new certificate.
I0317 22:15:16.040106       1 route.go:498] Finished syncing Route "openshift-console/console"
I0317 22:15:16.229268       1 route.go:226] Updating Route openshift-console/console RV=2585490->2585491 UID=71e8f2da-aaa0-4773-9a6c-dc3bc5ca90c4->71e8f2da-aaa0-4773-9a6c-dc3bc5ca90c4
I0317 22:15:16.229302       1 route.go:496] Started syncing Route "openshift-console/console"
I0317 22:15:16.229465       1 route.go:563] Route "openshift-console/console" needs new certificate: Route is missing CertKey
I0317 22:15:16.229789       1 route.go:607] Using ACME client with DirectoryURL "https://acme-v02.api.letsencrypt.org/directory"
I0317 22:16:04.288012       1 reflector.go:432] k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108: Watch close - *v1.LimitRange total 0 items received
I0317 22:16:16.229690       1 route.go:498] Finished syncing Route "openshift-console/console"
E0317 22:16:16.229768       1 route.go:1308] openshift-console/console failed with : 429 urn:ietf:params:acme:error:rateLimited: Error creating new order :: too many certificates already issued for exact set of domains: see https://letsencrypt.org/docs/rate-limits/

@tnozicka

**Comment by eehmann** [comment]
Hey Darren,

my current guess:
The Operator which manages the Openshift Web-Console is causing this problem.
As soon as the Let's Encrypt Certificate is added to the Route, the Operator removes it again.

I didn't find a solution yet, but maybe this information can help you.
