### ISSUE TITLE
E-Mail for account creation

### ISSUE THREAD

**Issue by tobru** [tnozicka/openshift-acme#26]
When creating an account for Let's Encrypt you normally pass an E-Mail address which then f.e. gets notifications when a certificate hasn't been renewed. How is this done in openshift-acme? What E-Mail address is used and would I be able to chose which one? A short look into the code didn't reveal aynthing.

**Comment by tnozicka** [comment]
@tobru I am writing this down from the top of my head but I think after a the account is created it creates secret with [annotation](https://github.com/tnozicka/openshift-acme/blob/da3caf917b43582dce8853b6e456c93b3c1026a6/pkg/openshift/account/account.go#L22). If you update the content of that annotation it should update the account as well.

Relevant code should be:
https://github.com/tnozicka/openshift-acme/blob/da3caf917b43582dce8853b6e456c93b3c1026a6/pkg/openshift/account/account.go#L86-L94
https://github.com/tnozicka/openshift-acme/blob/da3caf917b43582dce8853b6e456c93b3c1026a6/pkg/openshift/account/account.go#L166

While looking at it I see update called only on start up but it should be called anytime the annotation changes. If that's indeed not sync immediately we should track it in an issue and fix it.

**Comment by tobru** [comment]
Thanks for your answer. I guess it would make sense when the annotation is updated that the account also gets updated. Looking at #27: Depending on which account you'll be using once a global account is supported there are probably other challenges here. You'd want to use a "admin" mail address for a global account and for a project-local account you'd prefer the customers mail address.

**Comment by hypery2k** [comment]
did I got it right, that adding an annotation with an email value in "AnnotationAcmeAccountContactsKey" would work currently?

**Comment by hypery2k** [comment]
@tnozicka: I cannot find the correct code snippet, but looks like the point for contact email isn't there:

https://github.com/tnozicka/openshift-acme/blob/0e20941f721cc033eaba65db0335b8d6b6bdb07e/pkg/acme/client/builder/builder.go#L31-L50

**Comment by zdzichu** [comment]
/reopen
Hi, the ability to provide email for account is still needed. You propose creating the account, annotating it with email and wait to be synced.
Well, some ACME providers *require* email to *create* account. They fail at first step, so there is no account object to put annotation on.
One of such providers is BuyPass: https://www.buypass.com/ssl/products/acme
Endpoint for prod https://api.buypass.com/acme/directory , probably there's a staging one, too.

**Comment by seandilda** [comment]
@zdzichu this is doable with the current version of openshift-acme.  Just setup your issuer configmap to look something like:

```yaml
apiVersion: v1
data:
  cert-issuer.types.acme.openshift.io: |
    type: ACME
    acmeCertIssuer:
      account:
        contacts:
        - mailto:email@example.com
      directoryURL: https://api.buypass.com/acme/directory

```

**Comment by tnozicka** [comment]
yeah, I was just looking into why that wouldn't work

**Comment by zdzichu** [comment]
@seandilda Indeed, that works. Thanks for magic yaml!

**Comment by tnozicka** [comment]
btw. magic is defined here https://github.com/tnozicka/openshift-acme/blob/ed3303b/pkg/api/types.go#L36
