### ISSUE TITLE
Global ACME account

### ISSUE THREAD

**Issue by tobru** [tnozicka/openshift-acme#27]
The current implementation - as far as I understand - creates an ACME account per project. When having many projects this could lead into [rate-limit](https://letsencrypt.org/docs/rate-limits/) issues. Would it be possible to have one cluster-level ACME account for all projects?

**Comment by tnozicka** [comment]
I remember thinking about it as well when I started. I guess we could have an option to use only one ACME account for the controller, but I will need to think this through and how that impacts security.

2 possible workarounds from that time:
- Let's encrypt has a form and they will raise limits for you if you are a big and legitimate user
- I think there are Egresses in Kube/OpenShift that will let you form outgoing traffic to have different source IP

**Comment by tobru** [comment]
Thanks for your answer. We'll probably go for the form to raise the rate-limits. And if someday the controller supports having a global ACME account, we can then migrate to it.

**Comment by tnozicka** [comment]
@tobru I have talked to the Let's Encrypt folks and they told me they can only raise limits for the account. Based on this I am inclined to migrate openshift-acme for next release to use only one global account.

**Comment by tnozicka** [comment]
We will loose part of the flexibility we had and the controllers will have to do more security checks and rate limiting but I believe it will pay off.

**Comment by tobru** [comment]
@tnozicka Thanks a lot for getting back to this issue, really appreciate it.

I also think that having a global ACME account will pay off, especially for big clusters with many projects and customers like we have at APPUiO.

**Comment by tnozicka** [comment]
fixed in https://github.com/tnozicka/openshift-acme/pull/48
