### ISSUE TITLE
Support using specific endpoint per project and/or role

### ISSUE THREAD

**Issue by hansmi** [tnozicka/openshift-acme#30]
The Let's Encrypt CA supports [a staging endpoint](https://letsencrypt.org/docs/staging-environment/) which has [more relaxed rate limits](https://letsencrypt.org/docs/rate-limits/). It should be possible to use a specific endpoint per project and/or route to avoid running into rate limits during testing while the default endpoint is the production environment. This will likely need another annotation.

**Comment by tnozicka** [comment]
@hansmi would you mind describing the use case in more detail here? 

The main point of staging env is to test acme controllers/clients. As the controller is managing all projects/routes I see no point in provisioning only some of them from staging.

For the actual app development, certificates provisioned from staging are **invalid** so if you disable the annotation you can re-create your routes as you want and router will provide with default certificate which will be likely invalid as well.

**Comment by hansmi** [comment]
@tnozicka, the main use case of us at @VSHN would be end-to-end tests. Our monitoring creates two new projects per hour and waits until a deployed application is available via the routers (one each of S2I and Docker). We'd like to add the ACME controller into the mix to ensure that that part of the cluster also works for the average user. #27 will already help with avoiding limits, but considering that we're talking about ~48 projects per day we'd still prefer to use the staging endpoint. Obviously this is in addition to more specific monitoring, and we control the client for monitoring hence certificates signed by a staging CA are a non-issue.
