### ISSUE TITLE
Domain validation doesn't work with insecureEdgeTerminationPolicy: Redirect

### ISSUE THREAD

**Issue by aszs** [tnozicka/openshift-acme#38]
When my route had "insecureEdgeTerminationPolicy: Redirect" defined the controller was unable to validate the domain because the router tries to redirect when the .well-known challenge URL is requested. After I removed "insecureEdgeTerminationPolicy: Redirect" from the route definition the challenge URL responded correctly and the certificate was installed.

**Comment by tnozicka** [comment]
I think you are hitting OpenShift bug - check:
 - https://github.com/tnozicka/openshift-acme/issues/16#issuecomment-323087380
 - https://github.com/openshift/origin/pull/15847

**Comment by aszs** [comment]
Thanks, it does look like that's the bug and the fix -- do you expect your fix to make it into the openshift 3.7 release?

**Comment by tnozicka** [comment]
@aszs I don't think it will make it but I am willing to backport it if it gets merged into master

**Comment by tnozicka** [comment]
fixed (hacked) in https://github.com/tnozicka/openshift-acme/pull/48
