### ISSUE TITLE
acme-controller loops if project is being removed during registration

### ISSUE THREAD

**Issue by mhutter** [tnozicka/openshift-acme#42]
**What I did**
- Create new Project, deploy app
- annotate route with `kubernetes.io/tls-acme`
- remove project before acme-controller finished his work

**What I expected**
acme-controller would stop after getting an error

**What happened**
The first time around, acme-controller failed to save the new LetsEncrypt account because the Project was already removed. acme-controller then retried to create LE-accounts again and again, always erroring because it could not save the account.

After 10 times, we hit the 10 accounts/3h rate limit (and acme-controller loops forever)

---

During tests I created a new project to test the acme-controller. I was a bit too hastly and removed the project before acme-controller finished his job. This lead to the following situation:

```
INFO Creating new account in namespace mhu-test
TRACE Creating new account in namespace mhu-test finished
ERROR route.go:192 RouteController: doWatchIteration failed: acme.Done failed: secrets "acme-account" is forbidden: unable to create new content in namespace mhu-test because it is being terminated.
 INFO Creating new account in namespace mhu-test
TRACE Creating new account in namespace mhu-test finished
ERROR route.go:192 RouteController: doWatchIteration failed: acme.Done failed: namespaces "mhu-test" not found
 INFO Creating new account in namespace mhu-test
... repeated a couple of times ...
ERROR route.go:192 RouteController: doWatchIteration failed: acme.Done failed: 429 urn:acme:error:rateLimited: Error creating new registration :: too many registrations for this IP
 INFO Creating new account in namespace mhu-test
... repeated over and over again ...
```

**Comment by tnozicka** [comment]
Sorry about that. This will be fixed in next version where we will be also migrating to one global account as discussed in https://github.com/tnozicka/openshift-acme/issues/27

**Comment by mhutter** [comment]
Hey! I just had a similar issue; the ACME-controller tried to register an account for a Project that was already deleted, **even after restarting the acme-controller pod**.

Would it be possible to check if a project and route still exist before starting a new run?

**Comment by tnozicka** [comment]
that's strange (maybe the project was still being deleted and we forget to check for deletionTimestamp being nil) but it will be also fixed by the next version, most of the logic got rewritten and it will be using one global account

**Comment by tnozicka** [comment]
fixed in https://github.com/tnozicka/openshift-acme/pull/48
