### ISSUE TITLE
Fake LE Intermediate X1 root authority

### ISSUE THREAD

**Issue by raymccarthy** [tnozicka/openshift-acme#44]
Hi, 
This is a really cool project, thank you!  I am missing something really basic with the LE account and API key.  I have run the live deployment but all me certificates are being issued on the Fake LE Intermediate X1 authority.  I think this is because my account and key are not being used?

Is there a way of providing these details to the pod or am I doing something else wrong?

Thanks!
Ray

**Comment by tnozicka** [comment]
Hi @raymccarthy,

any chance you ran `-staging` before switching to `-live`? 

There is Kubernets Secret named `acme-account` created in every namespace (with acme route) that represents the ACME account and holds the key. It is not interchangeable with staging. You need to delete it as well as the provided certificate from your route and probably restart the controller to avoid cache.

**Comment by raymccarthy** [comment]
Thanks a million Tomas, that is exactly what I have done.  I'll delete the secrets and give it a try

**Comment by tnozicka** [comment]
yw; let me know how that went and close the issue if that got solved. 

FYI: In the next version openshift-acme will migrate to using one global account and there will be a warning if your account url doesn't match ACME_URL domain to help with cases like that.

**Comment by raymccarthy** [comment]
It worked perfectly, thank you!
