### ISSUE TITLE
Add support for route labels (router sharding)

### ISSUE THREAD

**Issue by anroots** [tnozicka/openshift-acme#45]
I'm running two OS3 routers: one "internal", one "public". The public router and routes exposed therein are accessible from the internet, the internal one is for LAN-only.

The public router only exposes routes that are labelled with (`router=public` (ENV `ROUTE_LABELS=router=public`)).

When `openshift-acme` creates the temporary `.well-known` route, it will be created without the `router` label and hence exposed on the local router. LetsEncrypt tries to verify the challenge, but gets a 404 response and fails.

Is there any way to work around this and tell `openshift-acme` the default labels the challenge route should get? Currently, I'm forced to disable `ROUTE_LABELS` and expose all routes to the Interwebs.

**Comment by tnozicka** [comment]
This isn't supported yet. It looks like a valid use case and shouldn't be hard to add.

**Comment by tnozicka** [comment]
As a workaround in the meantime: can you make the route to be public by default with selector like `router != private`

**Comment by hypery2k** [comment]
any change to get #69 merged?
