### ISSUE TITLE
how to trigger renew manually

### ISSUE THREAD

**Issue by djdevin** [tnozicka/openshift-acme#46]
Project works great - adds LE certificates to all tagged routes.

I'd like to trigger a renew manually somehow so I don't have to wait 3 months to see if this works.

I looked at the code and saw that it uses the certificate date which I likely can't backdate to test renewals.

Any way to "fake" trigger a renewal for testing?

**Comment by tnozicka** [comment]
I am not actually sure if you can do it manually. There is certificate cache inside and the certificate will get provisioned from there when you delete it and while it's still valid. 

This is getting rewritten and the cache will be removed in the next version.

**Comment by tnozicka** [comment]
With the new version just merged 
`oc patch route <name> -p '{"spec":{"tls":{"certificate":"","key":""}}}'`
should be enough
