### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Hertan** [tnozicka/openshift-acme#54]
`I0316 07:52:04.886094       1 route.go:483] Route "develop/origin": authorization state is "pending"`
`I0316 07:52:04.886148       1 client.go:83] Found 2 possible combinations for authorization`
`I0316 07:52:04.886157       1 client.go:90] Found 1 valid combinations for authorization`
`I0316 07:52:05.028449       1 exposer.go:283] Waiting for exposing route develop/origin-acme-sh4hx to be admitted.`
`I0316 07:52:05.071428       1 route.go:387] Finished syncing Route "develop/origin" (410.782748ms)`
`E0316 07:52:05.071889       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:573
/usr/local/go/src/runtime/panic.go:505
/usr/local/go/src/runtime/panic.go:63
/usr/local/go/src/runtime/signal_unix.go:388
/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/watch/until.go:41
/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/pkg/controllers/route/exposer.go:288
/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/pkg/acme/client/client.go:104
/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/pkg/controllers/route/route.go:489
/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/pkg/controllers/route/route.go:742
/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/pkg/controllers/route/route.go:749
/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/pkg/controllers/route/route.go:770
/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:2361
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x827fc1]
goroutine 83 [running]:
github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0xfc8c80, 0x18e8260)
	/usr/local/go/src/runtime/panic.go:505 +0x229
github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/watch.Until(0x6fc23ac00, 0x0, 0x0, 0xc42137b1c0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/watch/until.go:41 +0x51
github.com/tnozicka/openshift-acme/pkg/controllers/route.(*Exposer).Expose(0xc42051dc80, 0xc4200d8dc0, 0xc42037ae00, 0x12, 0xc4210b6cc0, 0x2b, 0x1210b00, 0xc42051a240)
	/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/pkg/controllers/route/exposer.go:288 +0x18f6
github.com/tnozicka/openshift-acme/pkg/acme/client.(*Client).AcceptAuthorization(0xc4203f4c00, 0x1211f00, 0xc42009a6c0, 0xc42105d500, 0xc42037ae00, 0x12, 0xc4211b5920, 0x0, 0xf, 0x54426c5446465754)
	/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/pkg/acme/client/client.go:104 +0x2ae
github.com/tnozicka/openshift-acme/pkg/controllers/route.(*RouteController).handle(0xc4204c60f0, 0xc42042a100, 0xe, 0x0, 0x0)
	/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/pkg/controllers/route/route.go:489 +0x21d0
github.com/tnozicka/openshift-acme/pkg/controllers/route.(*RouteController).processNextItem(0xc4204c60f0, 0xc420080400)
	/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/pkg/controllers/route/route.go:742 +0xde
github.com/tnozicka/openshift-acme/pkg/controllers/route.(*RouteController).runWorker(0xc4204c60f0)
	/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/pkg/controllers/route/route.go:749 +0x2b
github.com/tnozicka/openshift-acme/pkg/controllers/route.(*RouteController).(github.com/tnozicka/openshift-acme/pkg/controllers/route.runWorker)-fm()
	/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/pkg/controllers/route/route.go:770 +0x2a
github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc420014090)
	/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc420014090, 0x3b9aca00, 0x0, 0x4d4a706d54336c01, 0xc4200aa240)
	/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc420014090, 0x3b9aca00, 0xc4200aa240)
	/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/tnozicka/openshift-acme/pkg/controllers/route.(*RouteController).Run
	/opt/app-root/src/go/src/github.com/tnozicka/openshift-acme/pkg/controllers/route/route.go:770 +0x1b3
`

**Comment by tnozicka** [comment]
@Hertan thanks for the traceback, fix is in place https://github.com/tnozicka/openshift-acme/pull/55
