### ISSUE TITLE
support http/https proxies

### ISSUE THREAD

**Issue by patlachance** [tnozicka/openshift-acme#57]
Hello
In my setup, the openshift cluster is not directly attached to internet and need to use a squid proxy to reach internet. Standard linux environment variables are not used by the exposer.go component.

**Comment by brianredbeard** [comment]
@patlachance out of curiosity, how would resources outside of the cluster traverse back _into_ the cluster to be able to perform the cert validation.  Without that, there's not reason to implement forward proxy support.

**Comment by tnozicka** [comment]
fixed in https://github.com/tnozicka/openshift-acme/pull/58
