### ISSUE TITLE
[RFE] Support for wildcars

### ISSUE THREAD

**Issue by e-minguez** [tnozicka/openshift-acme#61]
It seems letsencrypt now supports [wildcards](https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579/) so maybe the controller can handle the renewal of the wildcard and modify the router secret.

**Comment by tnozicka** [comment]
> wildcard domains must be validated using the DNS-01 challenge type. This means that you’ll need to modify DNS TXT records in order to demonstrate control over a domain for the purpose of obtaining a wildcard certificate

using DNS validation only is not an easy start for us as that needs https://github.com/tnozicka/openshift-acme/issues/41 first

**Comment by tnozicka** [comment]
But yes, Router is the main target here with wildcard support.

We also need client (library) support for v2 (https://github.com/golang/go/issues/21081)

**Comment by djdevin** [comment]
assuming that verification works, what are the chances of having this work on multiple routes with the same certificate?  i.e. not just one route that is a wildcard route

example, we have a ton of apps that use the default route so there's abc.example.com, def.example.com, etc

right now we have to request individual certificates for all of those, which works great. but we frequently exhaust limits since the base "account" to Let's Encrypt is the same

**Comment by computate** [comment]
t is possible to generate wildcard certs with certbot/letsencrypt, I do it every 3 months. I did it a few days ago. You just have to point it to an updated server like this one: https://acme-v02.api.letsencrypt.org/directory

# get latest certs from certbot from DNS challenges.
sudo certbot -d example.com -d *.example.com -d *.apps.example.com -d example.org -d *.example.org -d *.apps.example.org –manual –preferred-challenges dns certonly –server https://acme-v02.api.letsencrypt.org/directory

**Comment by tnozicka** [comment]
fyi we will be switching to acme v2 this month I think, we might get some default DNS provides with new library

syncing the secret from another route/secret in the same namespace is an option, but I'd have to think it through when we switch and have wildcards

**Comment by Maniket-dev** [comment]
Hi @tnozicka  - is this openshift ACME controller implementation (https://github.com/tnozicka/openshift-acme ) only for 'Let's encrypt' CA  or we can use it for other Certificate Authority also ?  Thank you

**Comment by tnozicka** [comment]
It supports any CA supporting ACME protocol, Let's Encrypt is just one of the providers.

**Comment by Maniket-dev** [comment]
Thank you @tnozicka  . Just one query here , in case of a private CA , do we need to just make changes to below config map data and what is directory URL here.....

"cert-issuer.types.acme.openshift.io": '{"type":"ACME","acmeCertIssuer":{"directoryUrl":"https://acme-v02.api.letsencrypt.org/directory"}}'
