### ISSUE TITLE
Image versioning?

### ISSUE THREAD

**Issue by jperville** [tnozicka/openshift-acme#66]
Would it be possible to publish official releases of this project (applying to code and also to the docker image at https://hub.docker.com/r/tnozicka/openshift-acme), so that I can deploy your project without worrying about incompatible changes to environment variables, cluster roles etc?

I ask because I deployed your project many times in the past 8 months without any problems (after patching the openshift router to support updating the let's encrypt certificate when the route is secured with redirect insecure edge termination policy); on my latest deployment the acme controller fails to boot because of missing `OPENSHIFT_ACME_EXPOSER_IP` environment variable. I checked and since the cluster role has also changed I now have to retest my deployment to be compatible with the new image.

**Comment by cchaudier** [comment]
:+1: And if we can have also a releases tag to have a point in time. I want tu use this on production for one of my customers.

**Comment by hypery2k** [comment]
any update on this?
