### ISSUE TITLE
Allow setting controller default InsecureEdgeTerminationPolicy for Routes

### ISSUE THREAD

**Issue by tobru** [tnozicka/openshift-acme#7]
Would be great to have `InsecureEdgeTerminationPolicy` set to `Redirect` by default.

**Comment by tnozicka** [comment]
@tobru The default insecureEdgeTerminationPolicy in OpenShift is to disable traffic on the insecure scheme. I don't think it's in openshift-acme competency to decide that so it defaults to what OpenShift defaults to. If you want, you can change it or set it upfront on your Route and openshift-acme should honer it. If not that would be a bug.

**Comment by tobru** [comment]
Thanks for the feedback. May I suggest to make this setting configurable? F.e. `OPENSHIFT_ACME_DEFAULTREDIRECT=[true|false]`

IMHO most of the time you want to set `InsecureEdgeTerminationPolicy` to `Redirect` for a web application. When enabling ACME on a route, it would be great if I don't have to edit the route again to enable the redirect. Of course - as suggested - it could be done before, but I think it's more user-friendly if the ACME controller could take care of this.

**Comment by tnozicka** [comment]
@tobru seems reasonable

**Comment by tnozicka** [comment]
If we have that configurable I might be even inclined to have Redirect as default because, as you say, most people would expect it to be like that.

**Comment by christianh814** [comment]
+1 on this RFE

**Comment by tnozicka** [comment]
Fixed in #48

https://github.com/tnozicka/openshift-acme/blob/9e28fb3501268b7908cd2432f9900854405e30bf/pkg/cmd/cmd.go#L98
