### ISSUE TITLE
Scale / failover with multiple replica's

### ISSUE THREAD

**Issue by ajdevries** [tnozicka/openshift-acme#70]
This is a great project. Thanks for developing this and making it opensource. I'm running it on a new Openshift cluster and it works great.

A question, is it possible to run more `openshift-acme` pods? We're running multiple nodes on different servers (geo separated) and failover is interesting here.

**Comment by tnozicka** [comment]
> This is a great project. Thanks for developing this and making it opensource. I'm running it on a new Openshift cluster and it works great.

Thank you :)

> A question, is it possible to run more openshift-acme pods? We're running multiple nodes on different servers (geo separated) and failover is interesting here.

It isn't. In theory we could add master election so you could run it the same way as master controllers, with failover.

But does it really matter? You have a Deployment and if the node with the pod goes down, the deployment controller will spin up a new one on different node almost immediately. Given the provided service is asynchronous (a controller), I don't see a use case where this brief downtime would matter.

**Comment by ajdevries** [comment]
Thanks for the answer, and you're right, brief downtime doesn't matter.
