### ISSUE TITLE
Error: "exposer-ip" can't be empty string

### ISSUE THREAD

**Issue by magick93** [tnozicka/openshift-acme#71]
Hello

I have been using openshift-acme for several months without issues.

Today however, I started getting the following error:

```

I0625 03:53:03.773719       1 cmd.go:147] ACME server url is "https://acme-v01.api.letsencrypt.org/directory"
--
  | I0625 03:53:03.774132       1 cmd.go:154] ACME server loglevel == 8
  | I0625 03:53:03.774144       1 cmd.go:119] No kubeconfig specified, using InClusterConfig.
  | I0625 03:53:03.775687       1 cmd.go:170] Watching all namespaces.
  | I0625 03:53:03.775724       1 cmd.go:190] "selfnamespace" is unspecified, trying inCluster
  | Error: "exposer-ip" can't be empty string


```

Do you have any ideas as to what might cause this?

Thanks

**Comment by tnozicka** [comment]
I suspect this might be an issue with update. There has been few way how we have done exposing, 1 requiring Kubernetes Downward API. If you've updated the image, I'd check that you are running with the YAML definition for that deployment.

**Comment by magick93** [comment]
> If you've updated the image, I'd check that you are running with the YAML definition for that deployment.

Do you mean ensuring that routes that should be https have the following?

```
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
```

**Comment by tnozicka** [comment]
I meant the Deployment API definition for acme-controller itself.
https://github.com/tnozicka/openshift-acme/blob/master/deploy/letsencrypt-live/cluster-wide/deployment.yaml#L27-L30

**Comment by magick93** [comment]
Oh ok. I didnt realize there was this environment variable.

Currently it is set to `https://acme-v01.api.letsencrypt.org/directory`.

Is this the correct value? If not, what should it be?

Thanks

**Comment by tnozicka** [comment]
The link above is pointing to ` OPENSHIFT_ACME_EXPOSER_IP` variable, I don't suppose the value you've provided `https://acme-v01.api.letsencrypt.org/directory` is really there as the correct value is:
```yaml
        - name: OPENSHIFT_ACME_EXPOSER_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
```

**Comment by tnozicka** [comment]
I am not sure we are on the same page: I am telling you to set up env named `OPENSHIFT_ACME_EXPOSER_IP` and you keep talking about `OPENSHIFT_ACME_ACMEURL` :)
Those are 2 distinct env vars - `EXPOSER_IP != ACMEURL`

Maybe just run
```bash
oc apply -fhttps://raw.githubusercontent.com/tnozicka/openshift-acme/master/deploy/letsencrypt-live/cluster-wide/{clusterrole,serviceaccount,imagestream,deployment}.yaml
```
or just for the deployment
```
oc apply -fhttps://raw.githubusercontent.com/tnozicka/openshift-acme/master/deploy/letsencrypt-live/cluster-wide/deployment.yaml
```

**Comment by magick93** [comment]
My apologies! Yes, somewhere in my head these two had merged to one.

Thanks for your help. The issue is resolved.
