### ISSUE TITLE
no route to host

### ISSUE THREAD

**Issue by uocxp** [tnozicka/openshift-acme#77]
Updating Route from test/gohellouniverse UID=9e16ea55-94cd-11e8-9d8c-901b0efe13b8             RV=957432 to test/gohellouniverse UID=9e16ea55-94cd-11e8-9d8c-901b0efe13b8,RV=957432
--   I0731 14:37:31.162076       1 reflector.go:286] github.com/tnozicka/openshift-acme/pkg/cmd/cmd.go:261: 

forcing resync| W0731 14:39:32.589212  1 exposer.go:354] Failed to GET "http://test1.os.xxxxx.com/.well-known/acme-challenge/1E_AcMtAAtOTvtr4UZ4lgPKwsdPFlGrho3kacFoTAE":  Get  http://test1.os.xxxxx.com/.well-known/acme-challenge/1E_AcMtAAtOTvtr4UZ4lgPKwsdPFlGrho3kacFoTAE:  dial tcp xxx.xxx.xxx.xx:80: connect: no route to host

first : `github.com/tnozicka/openshift-acme/pkg/cmd/cmd.go` does not exist

second:  `Get  http://test1.os.xxxxx.com/.well-known/acme-challenge/1E_Ac MtAAtOTvtr4UZ4lgPKwsdPFlGrho3kacFoTAE:`  the colon is a part of the url which shouldn't be

**Comment by tnozicka** [comment]
> first : github.com/tnozicka/openshift-acme/pkg/cmd/cmd.go does not exist

doesn't it? https://github.com/tnozicka/openshift-acme/blob/master/pkg/cmd/cmd.go#L261

> second: Get http://test1.os.xxxxx.com/.well-known/acme-challenge/1E_Ac MtAAtOTvtr4UZ4lgPKwsdPFlGrho3kacFoTAE: the colon is a part of the url which shouldn't be

it isn't part of the URL, it's a standart way of separating Golang error messages, you can see it from the part of the message more left to it where it is quoted...
https://github.com/tnozicka/openshift-acme/blob/master/pkg/controllers/route/exposer.go#L354

>  dial tcp xxx.xxx.xxx.xx:80: connect: no route to host

https://github.com/tnozicka/openshift-acme/blob/master/pkg/controllers/route/exposer.go#-L328-L354

Looks like the IP:Port isn't accessible from your pods or in general.
