### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by foosinn** [tnozicka/openshift-acme#87]
Is this project still maintained? There are some pull requests i would like to see merged.

Sadly i am not experienced enough in go to maintain it.

**Comment by tnozicka** [comment]
Hi, it is still maintained. I have been really low on time lately, hopefully that gets better. I have been trying to get us running with OpenShift CI for several days in https://github.com/tnozicka/openshift-acme/pull/79 - once that's in, PRs get unblocked.

/close
