### ISSUE TITLE
Rename the annotation to a different namespace

### ISSUE THREAD

**Issue by Exordian** [tnozicka/openshift-acme#89]
Currently you're using `kubernetes.io/tls-acme` in your project. `kubernetes.io/` is/should already reserved for k8s core components [1]. If k8s ever implements an acme extension itself the nameclash could be bad. I'd suggest renaming it.

[1] https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set

**Comment by tnozicka** [comment]
Technically yes. The key here is that other projects in this area use the same annotation so we are compatible and interchangeable.

I'd not worry too much about the technicality here as kube is unlikely to claim it and we can migrate if that were to come. The compatibility wins for me. We could probably claim the annotation in kube as a shared point for such extensions but nobody has gone through the effort to do it.
