### ISSUE TITLE
 failed to get ACME authorization: 404 urn:acme:error:malformed: Expired authorization

### ISSUE THREAD

**Issue by miksonx** [tnozicka/openshift-acme#96]
Error

Failed to get ACME authorization: 404 urn:acme:error:malformed: Expired authorization 

**What happened**:
Everything was working normal. Today certificates are not reissued 

**What you expected to happen**:
Reissue certificate

**Environment**:
OKD 3.11

Image build
build-date=2019-03-06T02:42:38.249442
com.redhat.build-host=cpt-0004.osbs.prod.upshift.rdu2.redhat.com
io.openshift.build.commit.id=c7dfdab5feadc568a66261a8645dfc97a397893b

**Comment by tnozicka** [comment]
can you post the acme controller logs?

**Comment by miksonx** [comment]
Hi @tnozicka  
Sorry for posting this as bug but is not.
There was expired authorization because the ingress nodes ware restricted to verify public domain of issued challenge by the ACME service. We enabled proper route and the service was able to continue verifying issued .well-known/acme-challenge/<TOKEN>
Closing this.
